# GENERAL
# Set the default terminal type to support 256 colors
set -g default-terminal "tmux-256color"
# Enable true color support
set-option -a terminal-features 'alacritty:RGB'
# Disable mouse support
set -g mouse off

# STATUS BAR
# Turn the status bar on
set-option -g status on
# Status bar update interval
set -g status-interval 5
# Center-align window list
set -g status-justify centre

# COPY
setw -g mode-keys vi

# Bind home & end keys for vi copy mode
bind-key -T copy-mode-vi Home send-keys -X start-of-line
bind-key -T copy-mode-vi End send-keys -X end-of-line

# Space to begin selection, y to copy to clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
