# GENERAL
# Set the default terminal type to support 256 colors
set -g default-terminal "tmux-256color"
# Enable true color support
set-option -a terminal-features 'alacritty:RGB'
# Disable mouse support
set -g mouse off

# STATUS BAR
# Turn the status bar on
set-option -g status on
# Status bar update interval
set -g status-interval 5
# Center-align window list
set -g status-justify centre

# COPY
setw -g mode-keys emacs

# Bind home & end keys for standard copy mode
bind-key -T copy-mode Home send-keys -X start-of-line
bind-key -T copy-mode End send-keys -X end-of-line

# Fix text selection styles (optional but highly recommended)
# This lets you press Space to start selecting text, and 'y' to copy it
bind-key -T copy-mode y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
