# STATUS BAR
# Turn the status bar on
set-option -g status on
# Status bar update interval
set -g status-interval 5
# Center-align window list
set -g status-justify centre

# GENERAL
# Disable mouse support
set -g mouse off
# Use vi key bindings in copy mode
setw -g mode-keys vi
# Copy to system clipboard using xclip
# This binds the 'y' key to copy
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
