name: Lint

on: workflow_call

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Run linter
        run: make lint

      - name: Check the version is consistent
        run: make check_version
