name: Main

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "bundle.sh"
      - "install.sh"
      - "Makefile"
      - ".github/workflows/**"

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
